### ISSUE TITLE
Upgrade function cannot create new files

### ISSUE THREAD

**Issue by russelg** [savetheinternet/Tinyboard#41]
The new upgrade function, which I know is experimental at this time, cannot create files.

I found this bug while upgrading to commit 9c62a4d, I hadn't upgraded to the new events system yet, and when I tried to upgrade, it couldn't create the inc/events.php file. Even after it being created manually by me and chmodded to 777, the upgrade function still couldn't write to it.

Also, post.php is referencing the event function, but you haven't required inc/events.php.

**Comment by savetheinternet** [comment]
> Also, post.php is referencing the event function, but you haven't required inc/events.php.

It's included in `inc/functions.php`.

**Comment by russelg** [comment]
You did `require 'inc/events.php';` in functions lol

**Comment by savetheinternet** [comment]
Indeed I did, so that it wouldn't break external scripts made for older Tinyboard versions. Shouldn't be a problem.

In the future, i'd like to make `post.php` have just one `include`, which then includes the rest depending on what's needed.

Anyway, is the bug fixed now? I pushed a commit to try and solve it, but I haven't found the time to test it yet.

**Comment by russelg** [comment]
It appears you haven't committed anything.

**Comment by savetheinternet** [comment]
58baab6.
