### ISSUE TITLE
Banner scripts not working

### ISSUE THREAD

**Issue by surfer190** [savetheinternet/Tinyboard#90]
creating a simple script to echo a image of dimensions 300 x 100...in a file called banner.php in the default directory and enabling the banner in config-instance.php...

the image does not show

**Comment by komugifb** [comment]
Which script do you use?
I have concluded that for me it only works with the ones that waste a lot of bandwidth (load image everytime instead of redirecting to an image which you might have already loaded in cache).

I reccommend this one, never failed me: http://www.marcofolio.net/webdesign/php_random_image_rotation.html

**Comment by surfer190** [comment]
Yeah I put this in banners.php

<?php
$advert = array(); 
$advert[] = '<a href="link 2 here"><img src="banners/1.jpg"></a>';
//multiple adverts
$advert[] = '<a href="........></a>';
shuffle($advert); 
echo $advert[0];
?>

does not work

**Comment by Circlepuller** [comment]
Some ad-blocking plugins hide the image from displaying on pages - this could possibly be the issue you're encountering.

**Comment by surfer190** [comment]
Circlepuller, highly probable that you are correct. Just need to test.
