### ISSUE TITLE
Possible Backdoor

### ISSUE THREAD

**Issue by aliums** [savetheinternet/Tinyboard#99]
possible backdoor in tinyboard most recent version runs remote code via the eval function possibly could exist in older versions as well.

location: inc/mod/pages.php

https://github.com/savetheinternet/Tinyboard/blob/master/inc/mod/pages.php

lines 115 to 117

remove lines 108 too 149 to remove possible back-door, does not remove any functionality

text file could easily be a php script in disguise and be dynamic 

STI could specify in this php file say if $SERVER['remote_addr'] == "ip of image board he wants to run code on"
echo "sql query to delete database";
}

it was obviously intentional that STI is using eval for this function he could have easily just made use of the explode and implode functions in php
eval can run any code on your server which means if sti wants too he could run any code he wanted to on your website.

I advise you remove this code immediately as it does not impede any of the main functions website except that of the ability to check if the website is up to date which uses a function that could be easily exploited.

remote url code is retrieved from: http://tinyboard.org/version.txt

functions of eval in php: http://php.net/manual/en/function.eval.php

**Comment by savetheinternet** [comment]
Thanks for bringing this horrible security vulnerability to my attention.  I've fixed it in 1816218c64da5881c681808893ce8a9dc7eb54db and plan to issue a notice to all Tinyboard users about it (perhaps using this exploit to do so).

Believe it or not, this wasn't an intentional backdoor.  I haven't touched the update-checking code in a very, very long time (I think 2 years).  Sometimes I make bad decisions in my code and look back later and think "Why the heck would I do it like that?" and this is another one of those times.  Simply a product of my drunken coding and semi-incompetence.

I've fixed it in a way right now which won't interfere with previous versions.

If you happen to find any other vulnerabilities, please let me know.
